server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /guest
    username: guest
    password: guest
#    开启发送端确认
    publisher-confirms: true
#    开启消息持久化到队列的确认
    publisher-returns: true
#    只要抵达队列,以异步方式优先回调我们的回调接口
    template:
      mandatory: true

#    手动ack消息
    listener:
      simple:
        acknowledge-mode: manual
gmall:
  jwt:
    pubKeyPath: D:\\project-0722\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
alipay:
  app_id: 2016102900777005
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCM3oxAb9YAz9mFAcuG8fQAA7vEUClLkyrfGUJnBco+14oehaOi+yNaMMN8N2X733El2p/vWY2hoNfcS+aSGIuH/oiLFlfWN1ghg+CsP5eIFk9QGgxtoj+oQ2B6EXAeM+7zkXGU8WLdLBbmY4xnWFK6n5foBVe1tz8aSdk9QP68qeRcUy/BQcw+9Hdt3f67oCO7oqE+tAGm1uVjhvp+rrSH4weIjrBOQtw681wwiDj/xBSIipt4m8U781dAD0ehD12nYc2PTebfu+xKrM0kll+W/mNqTbaQKp+a0KKGXM9CHxOJienNhKi6dpBVmhxejymloHU3LByz9BZdjKr2arPZAgMBAAECggEAfwOOa+8qgvLlyuJyc4snGPhEzd4FTeo05pGs6J003PKUy65te9964bBEInUE1FSEfcAhIruZU1lmKHCbRbEx5f3feaE8s56VLSruYgC4jXCoNK439IYtZXbSv12HvQPQePbz9XqsTIWbZEHv76KYfUK2wfJHQkYmdHqPkIZQ6SPedyjtJCBTqXjv+wZfyHjDlbr5XZgGFHY3MYXqW+XvY7G/UjVEg1ynBzv1/N/JxKwC7nvcJZ5asQEMkkBCh0ZwTHGBLMIYzWWLoGvMxdYAICOmm3k3b/1pkJVWhFq3ApDDpzWOHAMe9TjFHjM5Vy+s9fkgMKMYDwGos3IdtFVk3QKBgQDhxXWbTES5SPrv1CpwB2X3PVv7b6RuF+4jG0EL6oEfX0H0BZz4XBh4Mtv5JHgZAUoQzFmilKJpsr6uPLrVmhfgljrT8ShP04Y4X2q8NxSCDVy9sBoWqS+9M6DL1mjm79Vdrq810Ii8J1dcC0+lcJ33Fge1XdocYL3ayBWzeC5ilwKBgQCfuvyQL2NcUPRsnVob99AnSthE1z9I/RLyx3tn8vRcQWsEh9U0XNJg3GDkYCzzBvBFUvKWtJx1bJrfwBWppJocqkc9R0vH+pjzjmkiTCtGnfJR+8JAxdAEqJnHwDlQUBIeCcbMklJjaIGX+xy9NwYQyJMhNJVV0Fw5Vb3fdbsbDwKBgQDR4v3od8jT75LJbpZdO6OBa5udbjaQ2tJZ9LZN255aifYIY0eAZC2jYLS7MzorFNXENBWIXWF3neJCnNacSPq1oTPjYKg3Pc/jjGDvxMzd8oorFhHKy1JENEDh/tvbBU94HjNodgsH0BMY0LMkfEN+Nw7Hfw6Lnywgvi3egHWu1QKBgQCZ8SKc6679N+B6FaTUs59fXxjUMAcEFzP93BepdVPg3gOAGFF458SyKXMQZ0iq6JMEnQ7EBEmOOh+BaaT3HHaTDeEew+nbUD+87BGTRommw27ZaKQsvPjgpIWhKDeUmbb8UDvSyWqx9/R+PzvReIhWAJkcNYt/axKXB3W5OcQcLQKBgH66QqsJ9HlPxVGSITodqBJob3nEc6uWTRDp3IvQnQQX+QeVF1WZKufEJRTAFB7CVAX3huNxIVW6oL621MkLMTizFd7jXN9WnoSefdnUxb+FYhTUmcphDEg2jwrF6fzyjaVS6cuuqXV365JqrWAbihPHAbAof6wMctQvAm5qHKDW
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiJrI8LVpY848f6dl/wThkFdMIsnRfSfzfJ/L4kWdD0mmn7sdKkQT+6kkiOaP4h052lcbRQ8qbHbkw5jjIqzDWMx4bDR9w8s58kmcINNKx5g2tmkQQw4hTMaKdEYpl4q/WL73dGgd2H1TNX3bcmgRrvXMF5zbZjhw1baLOUSkGnd6QGORF6/0v9LfrJ/cjfmesMtD8vIJjw3cr6qefZpYAeOtDVRxkNuIhHq3qMfq9B804oAAfOzAb8wsi4BZnDxTfqh0bJcBXR4+lONqGLIGgIns7NXNoXvYM8/7n+ViHGCb4YWop0JSOuXJXbsFEFfReqsTw/690UC3SvzplHQgywIDAQAB
#  支付成功的回调
  notify_url: http://localhost:8092/order/pay/success
#  支付成功返回的地址
  return_url: http://www.baidu.com
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

#
#alipay:
#  app_id: 2019081366221270
#  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCLR1yx2CQ319qFrobzxL+TtJBdIR6qeJcRx9uz+99NjSRcRXciBPfd3vheC8Yymid22DMISA68BADO4AzD3/9k/jxkaBzo2CP79gmawk7JPleLa4mG9d257hOBX5FwWxeg3C9ymhTdmCbGlbfZg5oDFhHw1b9F/6/URypegGW7ugJyWkdPvz3qgkDB7UzbQN25tNeQZ3l0AMf1pY4/LFHgw78zhOSmSbIng6OeguriUt8p5FCUDgJNZqfupQk9uwh9GMDK6i2hFYWcTR6AlLs6zfcdbk5PBBd2auyDMxSQcaJtsHzqLiLBA25iCwOAaeKdExrgsZHxB5tzu412ogi5AgMBAAECggEBAIed9w5czfdqQSeGJ3XZkEl8uk1UYI3RWhhAKRf6GxdiZZNLOJNxjwEFiYXZpSXEoMTCA/7+WwqMQ1UtKIDZ7c8jFx8VmYDIZVGD4xpENX8TKx9gmMtHQJ04ytlgezeSG1HQ1IqcqdCTxL39LsWntSFoLhP5rYO1Ujo7CXB3SZgeMoJ/fsuBo6K1HYA73iuitnRY1gYVbC3EpFu0apHVeCbmo9TC0hRtpi3s3TVgiGn4/9INw1/d+WQ62z5YTae4GKO/UPHz94yQn19BaFbsHS92uCaOGs+Wvs0yyQ+/R9OS8PinjxXR0ALvWnZ6qFwgfa4N7d+itDQzSL9A2BN9sgECgYEA5RIV5WtaVJPn4ttWJArQteu97JGZ6NBRevdC/9B0sKcgnh4/AHxzeTA52ZorjKa5w1QBwie5bHNS10UL+uQmYnwIZP2gx6UqApRhm3nc6/dKJj+50SseqpA2zA/q7S7AHoUccJWZiJC08KStSAx8y/leV+oU3lyNfbBz6IKrHCECgYEAm6b6AlKJW1kmwgrZsfeABnaiMLK+gRHC6tGo75HeB4l5XWu82YDiA61Cy9hmCyhHwMx3n7T1yOlUJ/vEOLR2Nu4SqJR4TgAPLwsYFT3qpygn4NPLkw+nt2uHXA+6Jp2wT0DK5Yg5FLvd4uX71A6k9adHLeyGRNi3prwXtSy/GZkCgYEAiKUPNrmhOs64BtV8PyfMdJjZxKLeQsjxsf6JkvwQf8hSZr/4KRwT7fjcqXeT/uT97wzPt7fmnlD028Euck1isGD4yPWa0T0vIDbPOuWo6YGsU8Cz4ZhtRKWeaoAcTbwTkqEo4+f5nENmDB7P1yjL0QlCRAM4y6Q+Kvn1Sn+X/sECgYEAmVCyh6EWzNSWmaEoZuS7xSILhd46SVXeYX+cYEWUpmXiFoPto2wQs8Bwv+rqMGk/rAd6eOQ9COXTUALsd1JB8r8zv7tmeKYUTqkl0p6HSJkEFq9noPZVpBSVYrfXCvxd0uKmN8qjNuoJl9oi3/CAybs4IGMOqjexRdmVnI5zuVkCgYAtqBwYYHUBPUWePVyyB5GZoIoHNJUnrH1yuSkg9A7xsBm6D2xOUTZ768ujX/2jA0D/041JLV47+qdvavaMN5WANJp2C6zK+C069M1LVKKBVupCkeq3btkq0Zrg5cAowl6YcdeBB1VjpDDe7nGTDPpisa/jtRKt9wyAYoQO5z5FFg==
#  alipay_public_key:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgxZsxMIhJeP1jsqbE+B9I/hNJurueUssru6hQ1sSPJ7IIdM8KIXYsGO/O1syH1gGFS1+mvPpk9kmvyuFsIeuYkjE4kbDf8KdaThezQSzgkbzW5Zbkx7Bm8Kt76ltBEVDZP+WzqNLpdZwcQeVz+IJ/JULojzkRNadxFh4Iry/mOX2IdjebKGpxYYrFUOq2L3dqHL3btKCmvGDsYLeER0OaQSW4KqksQQEHqPlnRLRjAI7IW2bHaFvfRXNB+QJ+lqZF+KjBIrYrYuys2SNC3BQ9yKi8rWa439nXXvz4OJ77eYthyFdTxYvj5RbZ1gO6t4sBbWlwoxU3+aJp5hQP5mGJQIDAQAB
#  #  支付成功的回调
#  notify_url: http://chennian.ngrok2.xiaomiqiu.cn/dyOrder/AppAliPayNotify
#  #  支付成功返回的地址
#  return_url: http://www.baidu.com
#  sign_type: RSA2
#  gatewayUrl: https://openapi.alipaydev.com/gateway.do
#  charset: utf-8
##  PayUrl: http://111.6.79.10:5100/aliPay/pay
##  selectUrl: http://111.6.79.10:5100/aliPay/transferQuery
##  refundUrl: http://111.6.79.10:5100/aliPay/refund
#
#
#weixin:
#  appid: wx4c0b364da1b44875
#  mchid: 1549453491
#  wechat_key: 221c749ed105b2de0dc0112460c30322
#  payChannel: weixin
#  NotifyUrl:  http://chennian.ngrok2.xiaomiqiu.cn/dyOrder/notify
#  PayUrl: http://111.6.79.10:5100/wechatPay/pay
#  selectUrl: http://111.6.79.10:5100/wechatPay/gettransferinfo
#  refundUrl: http://111.6.79.10:5100/wechatPay/refund
#
#  #  PayUrl: http://192.168.100.39:5100/wechatPay/pay
#  private_key: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDC+GdIViKk/vXi
#    eh0xBZ9nChVRST88xEiNAbpMakLvXHpyReJyliIEaSCA/qjFC5wBwS4PYQLuDe51
#    AYYVzqxvochjOk4G9AYzPnfs2HFK46vzgZuoaNPk+zSZ6SihOoV0kp5wSbeFD7Qo
#    nNTYBABnQZkRlGghzFIwgN6GV44uxZ/8pH3+R0TFBuJVfa8aw8jL/eMVeTCzMpe6
#    +BHiv00PyicS2/57Rhji9n8bnEfCCb+VyAW33Y/GcIZRw5vxLtOPd7Pi25qP67Ya
#    vz3CPY4twsmNUJ528gEx6DNyfNhlcKhUL6VBM4srxza354JsIRi1NfJskZME0CVQ
#    05Q8m7rZAgMBAAECggEBAJDao0mgDT9O2fo4xcVtKwAQAsSQyfXo0wpIVVR+wlo5
#    +BM8jsCZgI6MWITeLx+uv2qiTwlIBzg8i4TM7AT5ty19IndukxghZxXdfJYwPQPp
#    4RAapD5cG8oNRQhwrSoUY6C3ahV8/2dRwoVF9/DCEFam6wWfoDo0JoA4zps7I7zk
#    9CwELmn+3ZF7aicm5HGiMCUOMJBblmruYYo+CVA0Kd/QzMkXwa55aYM1Pm/Ku1bM
#    D6Cl3UCk+NHzylW9N6zrD+rg5pCubjGgBQkN+KugHMzko3xSiBa2tEGVZOE09N38
#    x0fa6jZQv/Kpd5O1LTjm1NLOxxBH3XcWYUitRyZq3DECgYEA8hhrxNOo+bNQlb48
#    UihqRT2k5alKMGZQI6tAsCUqseQKPXYVo4bAshq1kZQ2MQCH82auCzQbVZ1FmviA
#    +Q9vyhM9RVT9hj1aYptvlXenb5Qv+Jmz8siRUwwN8ERpp2bl9cgM0C+VN5xiv+cz
#    sCv7L+GsAx7zXZaw7IsK3OFVrWUCgYEAzisXwBcBfy0Gkc9dW13ay5hTKp1LYhRM
#    L/i7bWE0181bCUTtX5th6u9l6B+05SGmxxM5DUFpSquTOA9olBi7aP73P1EBSQUF
#    hEL2wIalR8RpFZRxehb6xtjFp8AUpGD+OOc37k3nH1QZi/M3BAOG84cMJBr8vLxk
#    scAuhAMQ6mUCgYEAisjZLxKvscXMEqvl5KtqkJsQJuBvuWNN2cTY5qHH4gb6n9VL
#    /lzHptKM+BHhJyJIzY41hBKxANmSB48iUKU6zrtMyqw4UnZllFXLGAJqKBrpjTh/
#    4lR8iwFEFFMDxoXEmqu+PLKqdiDes2iVRw9Phll2xKs/lI1Ii7IB3jIHbckCgYEA
#    k1qXchK/Xh9XV7XnWts8+1FW99lOvL4XKh5UD7xvYWKEE57xLelH1fvfUUYAK9ie
#    dCDYIRJEaDszUNkqfNckc8nv+5AxI/hz1fFqnXZfAWlvVh4v8PwlpyPeOaR+3HH6
#    ob8Y6blCXNDmJXHjO3ot5Tb7xX6Ib3kTWzwpwu7SE0UCgYEArsFGekF7YgMgoNY/
#    wxTYbUkdemDz/gt+eaDv3nigglbZBYYhB9m1Sw5RwVAWx+X9pyAA7Uj5Jdg0uxDd
#    +DIT26b53aYeMXKdZAsZV/cxfJdLNuD4mOzuQRcx0fmH3MgUkzYkQc5JVBqAdul4
#    M3rRooe3zhCBp4YsAr3awEQfWaA=
