server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.10
  rabbitmq:
    host: 192.168.56.10
    virtual-host: /guest
    username: guest
    password: guest
#    开启发送端确认
    publisher-confirms: true
#    开启消息持久化到队列的确认
    publisher-returns: true
#    只要抵达队列,以异步方式优先回调我们的回调接口
    template:
      mandatory: true

#    手动ack消息
    listener:
      simple:
        acknowledge-mode: manual
gmall:
  jwt:
    pubKeyPath: D:\\project-0722\\rsa\\rsa.pub # 公钥地址
    cookieName: GMALL_TOKEN
alipay:
  app_id: 2016101700705587
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCy/f6ysPx8lEB94QUgkPfPyE+zzDr9HEyz7uF7zjdn/r05E6JcIxn3k0/D15oSC/cECrO7kpSLkJ2xKqUx4sU/5lmpwm7hOtgKRklpf2Q0sHNWU78vcPrUV0/I6SF1fPTtNdnx1xKt6GkEDRO+ljU+QzvyyDvvJ8odxzAX6rBKOwQBb3+69EBOwMshQ41I1w7mHV9apP7Ub09z6N/mXmg+BNQFzFL0g5jr25n/0DfaxZ89i42T4epm/m5gbbyfotmD69yOlHxUjkABMaxmZV++IKq98sCLsuL6EDFOagDPXZbvMXs0FgySgnnzax12LmTsvJL9imK5Hquj/o1ez52lAgMBAAECggEBAJR++qZ/BQnJ6PNGEv3gp2c/1TficPH6X3xL68/N1tO1WIEY0/NCv9FQ6rUcktr0CDvXMSOlyQ08rkcEjUakz2ZjEfIvt9OuAPwNMeyPXrADz7xIAG44ejBeO3gASdzyDTUbHzRvbTTQgwd0XfQZJBUCrKKQEoEn7pvj2/eLojQB+X9JiV4xeV8nLsxYc1LoYeXIZhFU89Nlq+UZMc1HZ3aXx/wDAtPJlsQk7EiKVX5kJhYMSnaK5RiFU2iw4Ey7MrZ/yVUtqTyS+7MSYsjTCPi3yW/dQi1Qr/Pg/tMUlhiQx89n03JUdv5778Q2uR4A7d4dBYSs4mkwik2PdeaAD0ECgYEA9gwV+Gc8mmQBP1kuI2agsQGzX17SxNyoA2vnQmxXxC6jzYq3WGHm37usid62FVgkMvkN+rl/8BVI1VlOtblVDWc0IH+KxlQGtKvP2CZKmkRAlIjDbO1mHUmJI0npQINlvsnBMZNbuwmabyfvryUxRZC54iChVkMgjeJwjljVvDUCgYEAujuHNNPtefwXYZ2NM41D0wNB4WPKtNYhRxffiBRaGSwDqO5DbFLeNurswxo/m9ZhYvQS+SX704Puipi1Qys8tCl5oIKWLKlv8wCtgf01ZfeuFTh7cAauTijenj1wiN03yYfQEjWWuLXEr4gIOXOqdTZIXg2be3Jgd6+Wq+zUKbECgYBU38BoarxGCb9AafP3dDx0MsD8YgpUrEUswPkKObNg0jHhAjvSuhrZDLUs7e1jmX8LMkx3M6wFVmJEbkUvfJnxQKuDllt5pJyXkDjnN/Y+FtMsKa04EwBJlAdBbAqRHYJoeNIy1sEq2No0A9OzWCIR/CWS8myVBBzjtLvc7pn0DQKBgBvteWUustosN8VnvxkQAi/OuT53nJpp0iu7JMZfZvOHajUXJf1EoBZUPJU1hnx0Nb6FI6NBUvZxPoCCTgx4m23ZGmg7rRGdhzBF1b88nZlg/zYndjtihRkrf9bzF8Eui4MpXsacSrIAcDJyj+kts05IiamxGLP2fwjzyACYT2jBAoGBAPFGW4AJHIilWmJw9wR/Kod8Rcp2PfnkDdA7y6zpBAuImn2ACJVKLk9GilO4Tl1CJixSFhkaFOvrAIg11AEDtkq5WYFV/0hzUlRlB4ov7Oq3OlGLERhRGoZujvtnY/Bxyxp+iqhulcIo9HrDehP8roXGmKUJ8EujIuVOBVhEgc5Y
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1/Vh011ewdKcvnaMwzEMKRFSF1P3kfDc/+22tkxjFgODzhXFU1/zcyRW+573cVM29s1nhecEABpcKz3PmA/IRSKs8HuZhw2GNoojlXEgVNoFURmrUqeEZTiWf+xJNsV7/MjHbjHoqYbJW7OFsnuxdkCwzHXtC1tW8Od03hjLt8L4vlPneiWsIk16942mtUczbpMuaXfRQjXRJGr4eZump/VWwJeG9XZMK8ShyLL6OToWxNoygZBxYkfkV2PsVK7ha/7byD9S6f3zgrRQqteCJ0Ciclm4wgx3n3ohIx1pIHzWNfgqyM+Kl5I0u4KrdOUJrnGTtdhyA4/5D3ue9vY+WQIDAQAB
#  支付成功的回调
  notify_url: http://9glldacce2.52http.net/api/order/pay/success
#  支付成功返回的地址
  return_url: http://www.baidu.com
  sign_type: RSA2
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

#
#alipay:
#  app_id: 2019081366221270
#  merchant_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCLR1yx2CQ319qFrobzxL+TtJBdIR6qeJcRx9uz+99NjSRcRXciBPfd3vheC8Yymid22DMISA68BADO4AzD3/9k/jxkaBzo2CP79gmawk7JPleLa4mG9d257hOBX5FwWxeg3C9ymhTdmCbGlbfZg5oDFhHw1b9F/6/URypegGW7ugJyWkdPvz3qgkDB7UzbQN25tNeQZ3l0AMf1pY4/LFHgw78zhOSmSbIng6OeguriUt8p5FCUDgJNZqfupQk9uwh9GMDK6i2hFYWcTR6AlLs6zfcdbk5PBBd2auyDMxSQcaJtsHzqLiLBA25iCwOAaeKdExrgsZHxB5tzu412ogi5AgMBAAECggEBAIed9w5czfdqQSeGJ3XZkEl8uk1UYI3RWhhAKRf6GxdiZZNLOJNxjwEFiYXZpSXEoMTCA/7+WwqMQ1UtKIDZ7c8jFx8VmYDIZVGD4xpENX8TKx9gmMtHQJ04ytlgezeSG1HQ1IqcqdCTxL39LsWntSFoLhP5rYO1Ujo7CXB3SZgeMoJ/fsuBo6K1HYA73iuitnRY1gYVbC3EpFu0apHVeCbmo9TC0hRtpi3s3TVgiGn4/9INw1/d+WQ62z5YTae4GKO/UPHz94yQn19BaFbsHS92uCaOGs+Wvs0yyQ+/R9OS8PinjxXR0ALvWnZ6qFwgfa4N7d+itDQzSL9A2BN9sgECgYEA5RIV5WtaVJPn4ttWJArQteu97JGZ6NBRevdC/9B0sKcgnh4/AHxzeTA52ZorjKa5w1QBwie5bHNS10UL+uQmYnwIZP2gx6UqApRhm3nc6/dKJj+50SseqpA2zA/q7S7AHoUccJWZiJC08KStSAx8y/leV+oU3lyNfbBz6IKrHCECgYEAm6b6AlKJW1kmwgrZsfeABnaiMLK+gRHC6tGo75HeB4l5XWu82YDiA61Cy9hmCyhHwMx3n7T1yOlUJ/vEOLR2Nu4SqJR4TgAPLwsYFT3qpygn4NPLkw+nt2uHXA+6Jp2wT0DK5Yg5FLvd4uX71A6k9adHLeyGRNi3prwXtSy/GZkCgYEAiKUPNrmhOs64BtV8PyfMdJjZxKLeQsjxsf6JkvwQf8hSZr/4KRwT7fjcqXeT/uT97wzPt7fmnlD028Euck1isGD4yPWa0T0vIDbPOuWo6YGsU8Cz4ZhtRKWeaoAcTbwTkqEo4+f5nENmDB7P1yjL0QlCRAM4y6Q+Kvn1Sn+X/sECgYEAmVCyh6EWzNSWmaEoZuS7xSILhd46SVXeYX+cYEWUpmXiFoPto2wQs8Bwv+rqMGk/rAd6eOQ9COXTUALsd1JB8r8zv7tmeKYUTqkl0p6HSJkEFq9noPZVpBSVYrfXCvxd0uKmN8qjNuoJl9oi3/CAybs4IGMOqjexRdmVnI5zuVkCgYAtqBwYYHUBPUWePVyyB5GZoIoHNJUnrH1yuSkg9A7xsBm6D2xOUTZ768ujX/2jA0D/041JLV47+qdvavaMN5WANJp2C6zK+C069M1LVKKBVupCkeq3btkq0Zrg5cAowl6YcdeBB1VjpDDe7nGTDPpisa/jtRKt9wyAYoQO5z5FFg==
#  alipay_public_key:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgxZsxMIhJeP1jsqbE+B9I/hNJurueUssru6hQ1sSPJ7IIdM8KIXYsGO/O1syH1gGFS1+mvPpk9kmvyuFsIeuYkjE4kbDf8KdaThezQSzgkbzW5Zbkx7Bm8Kt76ltBEVDZP+WzqNLpdZwcQeVz+IJ/JULojzkRNadxFh4Iry/mOX2IdjebKGpxYYrFUOq2L3dqHL3btKCmvGDsYLeER0OaQSW4KqksQQEHqPlnRLRjAI7IW2bHaFvfRXNB+QJ+lqZF+KjBIrYrYuys2SNC3BQ9yKi8rWa439nXXvz4OJ77eYthyFdTxYvj5RbZ1gO6t4sBbWlwoxU3+aJp5hQP5mGJQIDAQAB
#  #  支付成功的回调
#  notify_url: http://chennian.ngrok2.xiaomiqiu.cn/dyOrder/AppAliPayNotify
#  #  支付成功返回的地址
#  return_url: http://www.baidu.com
#  sign_type: RSA2
#  gatewayUrl: https://openapi.alipaydev.com/gateway.do
#  charset: utf-8
##  PayUrl: http://111.6.79.10:5100/aliPay/pay
##  selectUrl: http://111.6.79.10:5100/aliPay/transferQuery
##  refundUrl: http://111.6.79.10:5100/aliPay/refund
#
#
#weixin:
#  appid: wx4c0b364da1b44875
#  mchid: 1549453491
#  wechat_key: 221c749ed105b2de0dc0112460c30322
#  payChannel: weixin
#  NotifyUrl:  http://chennian.ngrok2.xiaomiqiu.cn/dyOrder/notify
#  PayUrl: http://111.6.79.10:5100/wechatPay/pay
#  selectUrl: http://111.6.79.10:5100/wechatPay/gettransferinfo
#  refundUrl: http://111.6.79.10:5100/wechatPay/refund
#
#  #  PayUrl: http://192.168.100.39:5100/wechatPay/pay
#  private_key: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDC+GdIViKk/vXi
#    eh0xBZ9nChVRST88xEiNAbpMakLvXHpyReJyliIEaSCA/qjFC5wBwS4PYQLuDe51
#    AYYVzqxvochjOk4G9AYzPnfs2HFK46vzgZuoaNPk+zSZ6SihOoV0kp5wSbeFD7Qo
#    nNTYBABnQZkRlGghzFIwgN6GV44uxZ/8pH3+R0TFBuJVfa8aw8jL/eMVeTCzMpe6
#    +BHiv00PyicS2/57Rhji9n8bnEfCCb+VyAW33Y/GcIZRw5vxLtOPd7Pi25qP67Ya
#    vz3CPY4twsmNUJ528gEx6DNyfNhlcKhUL6VBM4srxza354JsIRi1NfJskZME0CVQ
#    05Q8m7rZAgMBAAECggEBAJDao0mgDT9O2fo4xcVtKwAQAsSQyfXo0wpIVVR+wlo5
#    +BM8jsCZgI6MWITeLx+uv2qiTwlIBzg8i4TM7AT5ty19IndukxghZxXdfJYwPQPp
#    4RAapD5cG8oNRQhwrSoUY6C3ahV8/2dRwoVF9/DCEFam6wWfoDo0JoA4zps7I7zk
#    9CwELmn+3ZF7aicm5HGiMCUOMJBblmruYYo+CVA0Kd/QzMkXwa55aYM1Pm/Ku1bM
#    D6Cl3UCk+NHzylW9N6zrD+rg5pCubjGgBQkN+KugHMzko3xSiBa2tEGVZOE09N38
#    x0fa6jZQv/Kpd5O1LTjm1NLOxxBH3XcWYUitRyZq3DECgYEA8hhrxNOo+bNQlb48
#    UihqRT2k5alKMGZQI6tAsCUqseQKPXYVo4bAshq1kZQ2MQCH82auCzQbVZ1FmviA
#    +Q9vyhM9RVT9hj1aYptvlXenb5Qv+Jmz8siRUwwN8ERpp2bl9cgM0C+VN5xiv+cz
#    sCv7L+GsAx7zXZaw7IsK3OFVrWUCgYEAzisXwBcBfy0Gkc9dW13ay5hTKp1LYhRM
#    L/i7bWE0181bCUTtX5th6u9l6B+05SGmxxM5DUFpSquTOA9olBi7aP73P1EBSQUF
#    hEL2wIalR8RpFZRxehb6xtjFp8AUpGD+OOc37k3nH1QZi/M3BAOG84cMJBr8vLxk
#    scAuhAMQ6mUCgYEAisjZLxKvscXMEqvl5KtqkJsQJuBvuWNN2cTY5qHH4gb6n9VL
#    /lzHptKM+BHhJyJIzY41hBKxANmSB48iUKU6zrtMyqw4UnZllFXLGAJqKBrpjTh/
#    4lR8iwFEFFMDxoXEmqu+PLKqdiDes2iVRw9Phll2xKs/lI1Ii7IB3jIHbckCgYEA
#    k1qXchK/Xh9XV7XnWts8+1FW99lOvL4XKh5UD7xvYWKEE57xLelH1fvfUUYAK9ie
#    dCDYIRJEaDszUNkqfNckc8nv+5AxI/hz1fFqnXZfAWlvVh4v8PwlpyPeOaR+3HH6
#    ob8Y6blCXNDmJXHjO3ot5Tb7xX6Ib3kTWzwpwu7SE0UCgYEArsFGekF7YgMgoNY/
#    wxTYbUkdemDz/gt+eaDv3nigglbZBYYhB9m1Sw5RwVAWx+X9pyAA7Uj5Jdg0uxDd
#    +DIT26b53aYeMXKdZAsZV/cxfJdLNuD4mOzuQRcx0fmH3MgUkzYkQc5JVBqAdul4
#    M3rRooe3zhCBp4YsAr3awEQfWaA=
